class Data {
  static List<Map<String, String>> currencies = [
    {
      "currency": "USD",
      "name": "United States Dollar",
      "symbol": "\$",
    },
    {
      "currency": "EUR",
      "name": "Euro",
      "symbol": "€",
    },
    {
      "currency": "GBP",
      "name": "British Pound",
      "symbol": "£",
    },
    {
      "currency": "NGN",
      "name": "Nigerian Naira",
      "symbol": "₦",
    },
    {
      "currency": "KES",
      "name": "Kenyan Shilling",
      "symbol": "KSh",
    },
    {
      "currency": "GHS",
      "name": "Ghanaian Cedi",
      "symbol": "GH₵",
    },
    {
      "currency": "ZAR",
      "name": "South African Rand",
      "symbol": "R",
    },
    {
      "currency": "XOF",
      "name": "West African CFA Franc",
      "symbol": "CFA",
    },
    {
      "currency": "XAF",
      "name": "Central African CFA Franc",
      "symbol": "CFA",
    },
    {
      "currency": "RWF",
      "name": "Rwandan Franc",
      "symbol": "FRw",
    },
    {
      "currency": "TZS",
      "name": "Tanzanian Shilling",
      "symbol": "TSh",
    },
    {
      "currency": "UGX",
      "name": "Ugandan Shilling",
      "symbol": "USh",
    },
    {
      "currency": "SLL",
      "name": "Sierra Leonean Leone",
      "symbol": "Le",
    },
    {
      "currency": "LRD",
      "name": "Liberian Dollar",
      "symbol": "L",
    },
    {
      "currency": "GMD",
      "name": "Gambian Dalasi",
      "symbol": "D",
    },
    {
      "currency": "GIP",
      "name": "Gibraltar Pound",
      "symbol": "£",
    },
    {
      "currency": "FKP",
      "name": "Falkland Islands Pound",
      "symbol": "£",
    },
    {
      "currency": "CUP",
      "name": "Cuban Peso",
      "symbol": "₱",
    },
    {
      "currency": "CUC",
      "name": "Cuban Convertible Peso",
      "symbol": "₱",
    },
    {
      "currency": "COP",
      "name": "Colombian Peso",
      "symbol": "COL\$",
    },
    {
      "currency": "CLP",
      "name": "Chilean Peso",
      "symbol": "CLP\$",
    },
    {
      "currency": "BRL",
      "name": "Brazilian Real",
      "symbol": "R\$",
    },
    {
      "currency": "BOB",
      "name": "Bolivian Boliviano",
      "symbol": "Bs",
    },
    {
      "currency": "ARS",
      "name": "Argentine Peso",
      "symbol": "AR\$",
    },
    {
      "currency": "AUD",
      "name": "Australian Dollar",
      "symbol": "A\$",
    },
    {
      "currency": "CAD",
      "name": "Canadian Dollar",
      "symbol": "C\$",
    },
    {
      "currency": "CNY",
      "name": "Chinese Yuan",
      "symbol": "¥",
    },
    {
      "currency": "JPY",
      "name": "Japanese Yen",
      "symbol": "¥",
    },
    {
      "currency": "INR",
      "name": "Indian Rupee",
      "symbol": "₹",
    },
    {
      "currency": "PKR",
      "name": "Pakistani Rupee",
      "symbol": "₨",
    },
    {
      "currency": "BDT",
      "name": "Bangladeshi Taka",
      "symbol": "৳",
    },
    {
      "currency": "LKR",
      "name": "Sri Lankan Rupee",
      "symbol": "₨",
    },
  ];

// generate a List exchange rate values between the currencies for 12 months
  static List<Map<String, dynamic>> exchangeRates = [
    {
      "currency": "USD",
      "rates": [
        {"month": "Jan", "rate": 1.0},
        {"month": "Feb", "rate": 1.0},
        {"month": "Mar", "rate": 1.0},
        {"month": "Apr", "rate": 1.0},
        {"month": "May", "rate": 1.0},
        {"month": "Jun", "rate": 1.0},
        {"month": "Jul", "rate": 1.0},
        {"month": "Aug", "rate": 1.0},
        {"month": "Sep", "rate": 1.0},
        {"month": "Oct", "rate": 1.0},
        {"month": "Nov", "rate": 1.0},
        {"month": "Dec", "rate": 1.0},
      ],
    },
    {
      "currency": "EUR",
      "rates": [
        {"month": "Jan", "rate": 0.8},
        {"month": "Feb", "rate": 0.9},
        {"month": "Mar", "rate": 0.7},
        {"month": "Apr", "rate": 0.6},
        {"month": "May", "rate": 0.5},
        {"month": "Jun", "rate": 0.4},
        {"month": "Jul", "rate": 0.3},
        {"month": "Aug", "rate": 0.2},
        {"month": "Sep", "rate": 0.1},
        {"month": "Oct", "rate": 0.2},
        {"month": "Nov", "rate": 0.3},
        {"month": "Dec", "rate": 0.4},
      ],
    },
    {
      "currency": "GBP",
      "rates": [
        {"month": "Jan", "rate": 0.7},
        {"month": "Feb", "rate": 0.8},
        {"month": "Mar", "rate": 0.6},
        {"month": "Apr", "rate": 0.5},
        {"month": "May", "rate": 0.4},
        {"month": "Jun", "rate": 0.3},
        {"month": "Jul", "rate": 0.2},
        {"month": "Aug", "rate": 0.1},
        {"month": "Sep", "rate": 0.2},
        {"month": "Oct", "rate": 0.3},
        {"month": "Nov", "rate": 0.4},
        {"month": "Dec", "rate": 0.5},
      ],
    },
    {
      "currency": "NGN",
      "rates": [
        {"month": "Jan", "rate": 600.0},
        {"month": "Feb", "rate": 1110.0},
        {"month": "Mar", "rate": 920.0},
        {"month": "Apr", "rate": 730.0},
        {"month": "May", "rate": 840.0},
        {"month": "Jun", "rate": 950.0},
        {"month": "Jul", "rate": 1160.0},
        {"month": "Aug", "rate": 1270.0},
        {"month": "Sep", "rate": 1380.0},
        {"month": "Oct", "rate": 1490.0},
        {"month": "Nov", "rate": 1500.0},
        {"month": "Dec", "rate": 1710.0},
      ],
    },
    {
      "currency": "KES",
      "rates": [
        {"month": "Jan", "rate": 100.0},
        {"month": "Feb", "rate": 110.0},
        {"month": "Mar", "rate": 120.0},
        {"month": "Apr", "rate": 130.0},
        {"month": "May", "rate": 140.0},
        {"month": "Jun", "rate": 150.0},
        {"month": "Jul", "rate": 160.0},
        {"month": "Aug", "rate": 170.0},
        {"month": "Sep", "rate": 180.0},
        {"month": "Oct", "rate": 190.0},
        {"month": "Nov", "rate": 200.0},
        {"month": "Dec", "rate": 210.0},
      ],
    },
    {
      "currency": "GHS",
      "rates": [
        {"month": "Jan", "rate": 10.0},
        {"month": "Feb", "rate": 20.0},
        {"month": "Mar", "rate": 30.0},
        {"month": "Apr", "rate": 40.0},
        {"month": "May", "rate": 50.0},
        {"month": "Jun", "rate": 60.0},
        {"month": "Jul", "rate": 70.0},
        {"month": "Aug", "rate": 80.0},
        {"month": "Sep", "rate": 90.0},
        {"month": "Oct", "rate": 100.0},
        {"month": "Nov", "rate": 110.0},
        {"month": "Dec", "rate": 120.0},
      ],
    },
    {
      "currency": "ZAR",
      "rates": [
        {"month": "Jan", "rate": 10.0},
        {"month": "Feb", "rate": 20.0},
        {"month": "Mar", "rate": 30.0},
        {"month": "Apr", "rate": 40.0},
        {"month": "May", "rate": 50.0},
        {"month": "Jun", "rate": 60.0},
        {"month": "Jul", "rate": 70.0},
        {"month": "Aug", "rate": 80.0},
        {"month": "Sep", "rate": 90.0},
        {"month": "Oct", "rate": 100.0},
        {"month": "Nov", "rate": 110.0},
        {"month": "Dec", "rate": 120.0},
      ],
    },
    {
      "currency": "XOF",
      "rates": [
        {"month": "Jan", "rate": 500.0},
        {"month": "Feb", "rate": 510.0},
        {"month": "Mar", "rate": 520.0},
        {"month": "Apr", "rate": 530.0},
        {"month": "May", "rate": 540.0},
        {"month": "Jun", "rate": 550.0},
        {"month": "Jul", "rate": 560.0},
        {"month": "Aug", "rate": 570.0},
        {"month": "Sep", "rate": 580.0},
        {"month": "Oct", "rate": 590.0},
        {"month": "Nov", "rate": 600.0},
        {"month": "Dec", "rate": 610.0},
      ],
    },
    {
      "currency": "XAF",
      "rates": [
        {"month": "Jan", "rate": 500.0},
        {"month": "Feb", "rate": 510.0},
        {"month": "Mar", "rate": 520.0},
        {"month": "Apr", "rate": 530.0},
        {"month": "May", "rate": 540.0},
        {"month": "Jun", "rate": 550.0},
        {"month": "Jul", "rate": 560.0},
        {"month": "Aug", "rate": 570.0},
        {"month": "Sep", "rate": 580.0},
        {"month": "Oct", "rate": 590.0},
        {"month": "Nov", "rate": 600.0},
        {"month": "Dec", "rate": 610.0},
      ],
    },
    {
      "currency": "RWF",
      "rates": [
        {"month": "Jan", "rate": 1000.0},
        {"month": "Feb", "rate": 1010.0},
        {"month": "Mar", "rate": 1020.0},
        {"month": "Apr", "rate": 1030.0},
        {"month": "May", "rate": 1040.0},
        {"month": "Jun", "rate": 1050.0},
        {"month": "Jul", "rate": 1060.0},
        {"month": "Aug", "rate": 1070.0},
        {"month": "Sep", "rate": 1080.0},
        {"month": "Oct", "rate": 1090.0},
        {"month": "Nov", "rate": 1100.0},
        {"month": "Dec", "rate": 1110.0},
      ],
    },
    {
      "currency": "TZS",
      "rates": [
        {"month": "Jan", "rate": 2000.0},
        {"month": "Feb", "rate": 2010.0},
        {"month": "Mar", "rate": 2020.0},
        {"month": "Apr", "rate": 2030.0},
        {"month": "May", "rate": 2040.0},
        {"month": "Jun", "rate": 2050.0},
        {"month": "Jul", "rate": 2060.0},
        {"month": "Aug", "rate": 2070.0},
        {"month": "Sep", "rate": 2080.0},
        {"month": "Oct", "rate": 2090.0},
        {"month": "Nov", "rate": 2100.0},
        {"month": "Dec", "rate": 2110.0},
      ],
    },
    {
      "currency": "UGX",
      "rates": [
        {"month": "Jan", "rate": 1000.0},
        {"month": "Feb", "rate": 1010.0},
        {"month": "Mar", "rate": 1020.0},
        {"month": "Apr", "rate": 1030.0},
        {"month": "May", "rate": 1040.0},
        {"month": "Jun", "rate": 1050.0},
        {"month": "Jul", "rate": 1060.0},
        {"month": "Aug", "rate": 1070.0},
        {"month": "Sep", "rate": 1080.0},
        {"month": "Oct", "rate": 1090.0},
        {"month": "Nov", "rate": 1100.0},
        {"month": "Dec", "rate": 1110.0},
      ],
    },
    {
      "currency": "SLL",
      "rates": [
        {"month": "Jan", "rate": 10000.0},
        {"month": "Feb", "rate": 10100.0},
        {"month": "Mar", "rate": 10200.0},
        {"month": "Apr", "rate": 10300.0},
        {"month": "May", "rate": 10400.0},
        {"month": "Jun", "rate": 10500.0},
        {"month": "Jul", "rate": 10600.0},
        {"month": "Aug", "rate": 10700.0},
        {"month": "Sep", "rate": 10800.0},
        {"month": "Oct", "rate": 10900.0},
        {"month": "Nov", "rate": 11000.0},
        {"month": "Dec", "rate": 11100.0},
      ],
    },
    {
      "currency": "LRD",
      "rates": [
        {"month": "Jan", "rate": 1000.0},
        {"month": "Feb", "rate": 1010.0},
        {"month": "Mar", "rate": 1020.0},
        {"month": "Apr", "rate": 1030.0},
        {"month": "May", "rate": 1040.0},
        {"month": "Jun", "rate": 1050.0},
        {"month": "Jul", "rate": 1060.0},
        {"month": "Aug", "rate": 1070.0},
        {"month": "Sep", "rate": 1080.0},
        {"month": "Oct", "rate": 1090.0},
        {"month": "Nov", "rate": 1100.0},
        {"month": "Dec", "rate": 1110.0},
      ],
    },
    {
      "currency": "GMD",
      "rates": [
        {"month": "Jan", "rate": 1000.0},
        {"month": "Feb", "rate": 1010.0},
        {"month": "Mar", "rate": 1020.0},
        {"month": "Apr", "rate": 1030.0},
        {"month": "May", "rate": 1040.0},
        {"month": "Jun", "rate": 1050.0},
        {"month": "Jul", "rate": 1060.0},
        {"month": "Aug", "rate": 1070.0},
        {"month": "Sep", "rate": 1080.0},
        {"month": "Oct", "rate": 1090.0},
        {"month": "Nov", "rate": 1100.0},
        {"month": "Dec", "rate": 1110.0},
      ],
    },
    {
      "currency": "GIP",
      "rates": [
        {"month": "Jan", "rate": 0.7},
        {"month": "Feb", "rate": 0.8},
        {"month": "Mar", "rate": 0.6},
        {"month": "Apr", "rate": 0.5},
        {"month": "May", "rate": 0.4},
        {"month": "Jun", "rate": 0.3},
        {"month": "Jul", "rate": 0.2},
        {"month": "Aug", "rate": 0.1},
        {"month": "Sep", "rate": 0.2},
        {"month": "Oct", "rate": 0.3},
        {"month": "Nov", "rate": 0.4},
        {"month": "Dec", "rate": 0.5},
      ],
    },
    {
      "currency": "FKP",
      "rates": [
        {"month": "Jan", "rate": 0.7},
        {"month": "Feb", "rate": 0.8},
        {"month": "Mar", "rate": 0.6},
        {"month": "Apr", "rate": 0.5},
        {"month": "May", "rate": 0.4},
        {"month": "Jun", "rate": 0.3},
        {"month": "Jul", "rate": 0.2},
        {"month": "Aug", "rate": 0.1},
        {"month": "Sep", "rate": 0.2},
        {"month": "Oct", "rate": 0.3},
        {"month": "Nov", "rate": 0.4},
        {"month": "Dec", "rate": 0.5},
      ],
    },
    {
      "currency": "CUP",
      "rates": [
        {"month": "Jan", "rate": 25.0},
        {"month": "Feb", "rate": 26.0},
        {"month": "Mar", "rate": 27.0},
        {"month": "Apr", "rate": 28.0},
        {"month": "May", "rate": 29.0},
        {"month": "Jun", "rate": 30.0},
        {"month": "Jul", "rate": 31.0},
        {"month": "Aug", "rate": 32.0},
        {"month": "Sep", "rate": 33.0},
        {"month": "Oct", "rate": 34.0},
        {"month": "Nov", "rate": 35.0},
        {"month": "Dec", "rate": 36.0},
      ],
    },
    {
      "currency": "CUC",
      "rates": [
        {"month": "Jan", "rate": 25.0},
        {"month": "Feb", "rate": 26.0},
        {"month": "Mar", "rate": 27.0},
        {"month": "Apr", "rate": 28.0},
        {"month": "May", "rate": 29.0},
        {"month": "Jun", "rate": 30.0},
        {"month": "Jul", "rate": 31.0},
        {"month": "Aug", "rate": 32.0},
        {"month": "Sep", "rate": 33.0},
        {"month": "Oct", "rate": 34.0},
        {"month": "Nov", "rate": 35.0},
        {"month": "Dec", "rate": 36.0},
      ],
    },
    {
      "currency": "COP",
      "rates": [
        {"month": "Jan", "rate": 3000.0},
        {"month": "Feb", "rate": 3010.0},
        {"month": "Mar", "rate": 3020.0},
        {"month": "Apr", "rate": 3030.0},
        {"month": "May", "rate": 3040.0},
        {"month": "Jun", "rate": 3050.0},
        {"month": "Jul", "rate": 3060.0},
        {"month": "Aug", "rate": 3070.0},
        {"month": "Sep", "rate": 3080.0},
        {"month": "Oct", "rate": 3090.0},
        {"month": "Nov", "rate": 3100.0},
        {"month": "Dec", "rate": 3110.0},
      ],
    },
    {
      "currency": "CLP",
      "rates": [
        {"month": "Jan", "rate": 500.0},
        {"month": "Feb", "rate": 510.0},
        {"month": "Mar", "rate": 520.0},
        {"month": "Apr", "rate": 530.0},
        {"month": "May", "rate": 540.0},
        {"month": "Jun", "rate": 550.0},
        {"month": "Jul", "rate": 560.0},
        {"month": "Aug", "rate": 570.0},
        {"month": "Sep", "rate": 580.0},
        {"month": "Oct", "rate": 590.0},
        {"month": "Nov", "rate": 600.0},
        {"month": "Dec", "rate": 610.0},
      ],
    },
    {
      "currency": "BRL",
      "rates": [
        {"month": "Jan", "rate": 5.0},
        {"month": "Feb", "rate": 6.0},
        {"month": "Mar", "rate": 7.0},
        {"month": "Apr", "rate": 8.0},
        {"month": "May", "rate": 9.0},
        {"month": "Jun", "rate": 10.0},
        {"month": "Jul", "rate": 11.0},
        {"month": "Aug", "rate": 12.0},
        {"month": "Sep", "rate": 13.0},
        {"month": "Oct", "rate": 14.0},
        {"month": "Nov", "rate": 15.0},
        {"month": "Dec", "rate": 16.0},
      ],
    },
    {
      "currency": "BOB",
      "rates": [
        {"month": "Jan", "rate": 5.0},
        {"month": "Feb", "rate": 6.0},
        {"month": "Mar", "rate": 7.0},
        {"month": "Apr", "rate": 8.0},
        {"month": "May", "rate": 9.0},
        {"month": "Jun", "rate": 10.0},
        {"month": "Jul", "rate": 11.0},
        {"month": "Aug", "rate": 12.0},
        {"month": "Sep", "rate": 13.0},
        {"month": "Oct", "rate": 14.0},
        {"month": "Nov", "rate": 15.0},
        {"month": "Dec", "rate": 16.0},
      ],
    },
    {
      "currency": "ARS",
      "rates": [
        {"month": "Jan", "rate": 100.0},
        {"month": "Feb", "rate": 110.0},
        {"month": "Mar", "rate": 120.0},
        {"month": "Apr", "rate": 130.0},
        {"month": "May", "rate": 140.0},
        {"month": "Jun", "rate": 150},
        {"month": "Jul", "rate": 160.0},
        {"month": "Aug", "rate": 170.0},
        {"month": "Sep", "rate": 180.0},
        {"month": "Oct", "rate": 190.0},
        {"month": "Nov", "rate": 200.0},
        {"month": "Dec", "rate": 210.0},
      ],
    },
    {
      "currency": "AUD",
      "rates": [
        {"month": "Jan", "rate": 1.0},
        {"month": "Feb", "rate": 1.0},
        {"month": "Mar", "rate": 1.0},
        {"month": "Apr", "rate": 1.0},
        {"month": "May", "rate": 1.0},
        {"month": "Jun", "rate": 1.0},
        {"month": "Jul", "rate": 1.0},
        {"month": "Aug", "rate": 1.0},
        {"month": "Sep", "rate": 1.0},
        {"month": "Oct", "rate": 1.0},
        {"month": "Nov", "rate": 1.0},
        {"month": "Dec", "rate": 1.0},
      ],
    },
    {
      "currency": "CAD",
      "rates": [
        {"month": "Jan", "rate": 1.0},
        {"month": "Feb", "rate": 1.0},
        {"month": "Mar", "rate": 1.0},
        {"month": "Apr", "rate": 1.0},
        {"month": "May", "rate": 1.0},
        {"month": "Jun", "rate": 1.0},
        {"month": "Jul", "rate": 1.0},
        {"month": "Aug", "rate": 1.0},
        {"month": "Sep", "rate": 1.0},
        {"month": "Oct", "rate": 1.0},
        {"month": "Nov", "rate": 1.0},
        {"month": "Dec", "rate": 1.0},
      ],
    },
    {
      "currency": "CNY",
      "rates": [
        {"month": "Jan", "rate": 6.0},
        {"month": "Feb", "rate": 6.0},
        {"month": "Mar", "rate": 6.0},
        {"month": "Apr", "rate": 6.0},
        {"month": "May", "rate": 6.0},
        {"month": "Jun", "rate": 6.0},
        {"month": "Jul", "rate": 6.0},
        {"month": "Aug", "rate": 6.0},
        {"month": "Sep", "rate": 6.0},
        {"month": "Oct", "rate": 6.0},
        {"month": "Nov", "rate": 6.0},
        {"month": "Dec", "rate": 6.0},
      ],
    },
    {
      "currency": "JPY",
      "rates": [
        {"month": "Jan", "rate": 100.0},
        {"month": "Feb", "rate": 100.0},
        {"month": "Mar", "rate": 100.0},
        {"month": "Apr", "rate": 100.0},
        {"month": "May", "rate": 100.0},
        {"month": "Jun", "rate": 100.0},
        {"month": "Jul", "rate": 100.0},
        {"month": "Aug", "rate": 100.0},
        {"month": "Sep", "rate": 100.0},
        {"month": "Oct", "rate": 100.0},
        {"month": "Nov", "rate": 100.0},
        {"month": "Dec", "rate": 100.0},
      ],
    },
    {
      "currency": "INR",
      "rates": [
        {"month": "Jan", "rate": 70.0},
        {"month": "Feb", "rate": 70.0},
        {"month": "Mar", "rate": 70.0},
        {"month": "Apr", "rate": 70.0},
        {"month": "May", "rate": 70.0},
        {"month": "Jun", "rate": 70.0},
        {"month": "Jul", "rate": 70.0},
        {"month": "Aug", "rate": 70.0},
        {"month": "Sep", "rate": 70.0},
        {"month": "Oct", "rate": 70.0},
        {"month": "Nov", "rate": 70.0},
        {"month": "Dec", "rate": 70.0},
      ],
    },
    {
      "currency": "PKR",
      "rates": [
        {"month": "Jan", "rate": 100.0},
        {"month": "Feb", "rate": 100.0},
        {"month": "Mar", "rate": 100.0},
        {"month": "Apr", "rate": 100.0},
        {"month": "May", "rate": 100.0},
        {"month": "Jun", "rate": 100.0},
        {"month": "Jul", "rate": 100.0},
        {"month": "Aug", "rate": 100.0},
        {"month": "Sep", "rate": 100.0},
        {"month": "Oct", "rate": 100.0},
        {"month": "Nov", "rate": 100.0},
        {"month": "Dec", "rate": 100.0},
      ],
    },
    {
      "currency": "BDT",
      "rates": [
        {"month": "Jan", "rate": 85.0},
        {"month": "Feb", "rate": 85.0},
        {"month": "Mar", "rate": 85.0},
        {"month": "Apr", "rate": 85.0},
        {"month": "May", "rate": 85.0},
        {"month": "Jun", "rate": 85.0},
        {"month": "Jul", "rate": 85.0},
        {"month": "Aug", "rate": 85.0},
        {"month": "Sep", "rate": 85.0},
        {"month": "Oct", "rate": 85.0},
        {"month": "Nov", "rate": 85.0},
        {"month": "Dec", "rate": 85.0},
      ],
    },
    {
      "currency": "LKR",
      "rates": [
        {"month": "Jan", "rate": 200.0},
        {"month": "Feb", "rate": 200.0},
        {"month": "Mar", "rate": 200.0},
        {"month": "Apr", "rate": 200.0},
        {"month": "May", "rate": 200.0},
        {"month": "Jun", "rate": 200.0},
        {"month": "Jul", "rate": 200.0},
        {"month": "Aug", "rate": 200.0},
        {"month": "Sep", "rate": 200.0},
        {"month": "Oct", "rate": 200.0},
        {"month": "Nov", "rate": 200.0},
        {"month": "Dec", "rate": 200.0},
      ],
    },
  ];
}
